### PR TITLE
Add controller and routes

### PR DESCRIPTION
**Pull request by aleksandarpetrushev**
@adrianthedev  when I visit `http://localhost:3000/rails_webhooks/subscribers`, 
errors with: `RailsWebhooks::SubscribersController#show is missing a template for request formats: text/html`
it is trying to call the show action instead of index. Any ideas?

### CODE REVIEW

**Comment by adrianthedev** [comment]
I pushed some code to fix that.

There were two things there:

1. the `routes.rb` file had `resource` instead of `resources` (plural). That's why it was looking for the `show.html.erb` file instead of `index.html.erb`
2. The `index.html.erb` file needs to be namespaced with the engine name in the `views` directory `app/views/rails_webhooks/subscribers/index.html.erb`

**Comment by aleksandarpetrushev** [comment]
Thanks a lot. I was aware of 2., just did not do it yet. Tomorrow I am planning to do the interface

**Comment by adrianthedev** [comment]
That sounds good! I'd recommend not to focus on estethics at all in the beginning. Don't worry about styles, layouts, etc. Just black text on white background.

**Comment by aleksandarpetrushev** [comment]
TODO: pagination for index, make destroy subscriber work, allow creating new and editing existing subscriber

**Pull request merged**
