### PR TITLE
Add module for registering webhook events on the Model level

### PR DESCRIPTION
**Pull request by aleksandarpetrushev**
example behaviour

``` 
RailsWebhooks::ExampleModel.registered_events
 => [:create, :test] 
 ```

### CODE REVIEW

**Comment by aleksandarpetrushev** [comment]
I am going to want to add a check for invalid events here

**Comment by aleksandarpetrushev** [comment]
@adrianthedev is something like this that you had in mind?

**Comment by adrianthedev** [comment]
Yes, this looks good.

The only think I would do differently is to register them in a different place than the model.
Somewhere on the engine side.

I'll explain. No, if you want to get all the events, you need to go through all models and get that property.

If you were to att it somewhere like `RailsWebhooks.events` (or something similar), you don't care about the models.
Now, for registration, you also need to send in the model where those events were registered.

**Comment by aleksandarpetrushev** [comment]
> Yes, this looks good.
> 
> The only think I would do differently is to register them in a different place than the model. Somewhere on the engine side.
> 
> I'll explain. No, if you want to get all the events, you need to go through all models and get that property.
> 
> If you were to att it somewhere like `RailsWebhooks.events` (or something similar), you don't care about the models. Now, for registration, you also need to send in the model where those events were registered.

@adrianthedev  I do not follow fully. You mean we should register events and models in a separate place on the engine side and have something like:
```ruby
{
  create: [Model1, Model2],
  update: [Model2],
  custom_event: [Model3]
.
.
.
}
```

**Comment by adrianthedev** [comment]
So, you'd register the events as you do now, but store them in a different place on the engine.
```ruby
class User
  register_webhooks :create, :update
end

class Comment
  register_webhooks :create, :update, :delete, :custom_event
  # we'll figure out custom events later
end

RailsWebhooks.get_events
# would yield the results below
[
  {
    class_name: "User",
    events: [:create, :update]
  },
  {
    class_name: "Comment",
    events: [:create, :update, :delete, :custom_event]
  }
]
```

**Comment by adrianthedev** [comment]
Does that make more sense?

**Comment by aleksandarpetrushev** [comment]
Yes it makes perfect sense

**Comment by aleksandarpetrushev** [comment]
@adrianthedev changes are made

**Review by adrianthedev — APPROVED** [review]
Hey @aleksandarpetrushev. This looks good! We have a good base!

**Pull request merged**
